export const AUTH_CREATE_PATH = "/auth/create"
export const AUTH_UNLOCK_PATH = "/auth/unlock"
export const AUTH_IMPORT_PATH = "/auth/import"
export const USER_PATH = "/user"
export const USER_APPS_PATH = "/user/apps"
export const USER_SETTINGS_PATH = "/user/settings"
export const USER_WORKER_PATH = "/user/worker"
